name: w3c_event_source
version: 1.3.2
description: W3C EventSource client implementation for Dart / Flutter,
  to communicate with server-sent event endpoints.
author: Renée Kooi <renee@kooi.me>
homepage: https://github.com/goto-bus-stop/dart-event-source

environment:
  sdk: ">3.0.0"
dependencies:
  test: ^1.24.3
